In [ ]:
# Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Generate a 3x3 array with random integers between 0 and 100
array_3x3 = np.random.randint(0, 101, (3, 3))

# Transpose the array (interchange rows and columns)
transpose_array = array_3x3.T

# Print the original and transposed arrays
print("A 3x3 Array with random integers between 1 and 100:\n", array_3x3)
print("Array after interchanging its rows and columns:\n", transpose_array)


A 3x3 Array with random integers between 1 and 100:
 [[41 16 87]
 [ 7  0 17]
 [65 40 89]]
Array after interchanging its rows and columns:
 [[41  7 65]
 [16  0 40]
 [87 17 89]]


In [ ]:
# Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Generate a 1D array with 10 elements (0 to 9)
initial_array = np.arange(10)

# Reshape the 1D array into a 2x5 array
array_2x5 = initial_array.reshape((2, 5))

# Reshape the 2x5 array into a 5x2 array
array_5x2 = array_2x5.reshape((5, 2))

# Print the original array and the reshaped arrays
print("The original 1D array is:", initial_array)
print("Reshaped 2x5 array:\n", array_2x5)
print("Reshaped 5x2 array:\n", array_5x2)

The original 1D array is: [0 1 2 3 4 5 6 7 8 9]
Reshaped 2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped 5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Create a 4x4 array with random float values
random_float_4x4 = np.random.rand(4, 4)

# Create a 6x6 array filled with zeros (to serve as the border)
zeros_6x6 = np.zeros((6, 6), dtype=float)

# Place the 4x4 array in the center of the 6x6 array
zeros_6x6[1:-1, 1:-1] = random_float_4x4

# Print the resulting 6x6 array
print("4x4 array with random float values:\n", random_float_4x4)

print("6x6 array with a border of zeros:\n", zeros_6x6)


4x4 array with random float values:
 [[0.83368492 0.28382963 0.85662594 0.82161337]
 [0.79475339 0.88989822 0.42555051 0.3041689 ]
 [0.61245641 0.68215469 0.82120933 0.72466713]
 [0.94383804 0.06789861 0.0603325  0.99570669]]
6x6 array with a border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.83368492 0.28382963 0.85662594 0.82161337 0.        ]
 [0.         0.79475339 0.88989822 0.42555051 0.3041689  0.        ]
 [0.         0.61245641 0.68215469 0.82120933 0.72466713 0.        ]
 [0.         0.94383804 0.06789861 0.0603325  0.99570669 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
# Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_step5 = np.arange(10, 61, 5)

# Print the resulting array
print("An array of integers from 10 to 60 with a step of 5 is:", array_step5)


An array of integers from 10 to 60 with a step of 5 is: [10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
#Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(uppercase_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)

# Print the original array and transformed arrays
print("Original array:")
print(string_array)
print()

print("Uppercase array:")
print(uppercase_array)
print()

print("Lowercase array:")
print(lowercase_array)
print()

print("Title case array:")
print(titlecase_array)
print()

print("Capitalized array:")
print(capitalize_array)


Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

Title case array:
['Python' 'Numpy' 'Pandas']

Capitalized array:
['Python' 'Numpy' 'Pandas']


In [ ]:
# Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays with random integers
a_int = np.random.randint(10, 20, (3, 3))
b_float = np.random.randint(50, 100, (3, 3))

# Perform element-wise operations
addition = a_int + b_float
subtraction = b_float - a_int
multiplication = a_int * b_float
division = b_float / a_int

# Print the arrays and results
print("Array 1 = \n", a_int)
print("Array 2 = \n", b_float)
print("Addition = \n", addition)
print("Subtraction = \n", subtraction)
print("Multiplication = \n", multiplication)
print("Division = \n", division)


Array 1 = 
 [[11 10 12]
 [19 11 18]
 [10 12 10]]
Array 2 = 
 [[79 67 93]
 [88 62 69]
 [53 63 75]]
Addition = 
 [[ 90  77 105]
 [107  73  87]
 [ 63  75  85]]
Subtraction = 
 [[68 57 81]
 [69 51 51]
 [43 51 65]]
Multiplication = 
 [[ 869  670 1116]
 [1672  682 1242]
 [ 530  756  750]]
Division = 
 [[7.18181818 6.7        7.75      ]
 [4.63157895 5.63636364 3.83333333]
 [5.3        5.25       7.5       ]]


In [ ]:
# Q8: Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

import numpy as np

# Create a 5x5 identity matrix using NumPy
identity_matrix = np.identity(5)

# Function to extract diagonal elements
def extract_diagonal(matrix):
    diagonal_elements = []
    for i in range(5):
        diagonal_elements.append(matrix[i, i])
    return diagonal_elements

# Call the function to get diagonal elements
diagonal_elements = extract_diagonal(identity_matrix)

# Display results
print("Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1.0, 1.0, 1.0, 1.0, 1.0]


In [ ]:
#Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
y = np.random.randint(0, 1001, 100)

# Function to check if a number is prime
def checking_prime(x):
    if x < 2:
        return False
    if x == 2:
        return True
    if x % 2 == 0:
        return False

    maximum_range = int(x**0.5) + 1
    for i in range(3, maximum_range, 2):
        if x % i == 0:
            return False
    return True

# Function to find all prime numbers in the array
def find_primes(array):
    prime_numbers = []
    for num in array:
        if checking_prime(num):
            prime_numbers.append(num)
    return prime_numbers

# Find and display all prime numbers in the generated array
prime_list = find_primes(y)
print("Prime numbers in the array:")
print(prime_list)


Prime numbers in the array:
[997, 811, 439, 359, 809, 701, 593, 109, 991, 109, 293, 557, 853, 269, 23, 587]


In [ ]:
#Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

# Daily temperatures for June
Temp_list = [30, 32, 30, 31, 31, 31, 30, 30, 31, 31, 31, 29, 31, 32, 31, 31, 31, 31, 31, 29, 30, 29, 29, 28, 29, 29, 27, 31, 31, 30]

# Convert the list to a NumPy array
June_temp = np.array(Temp_list, dtype=float)

# Calculate weekly averages
week_1 = np.mean(June_temp[0:7])
week_2 = np.mean(June_temp[7:14])
week_3 = np.mean(June_temp[14:21])
week_4 = np.mean(June_temp[21:28])

# Display the daily temperatures
print(f"Daily temperatures for June: \n{June_temp}\n")

# Display the weekly averages
print(f"The weekly averages are as follows:\n Week 1 : {week_1} \n Week 2 : {week_2} \n Week 3 : {week_3} \n Week 4 : {week_4}")


Daily temperatures for June: 
[30. 32. 30. 31. 31. 31. 30. 30. 31. 31. 31. 29. 31. 32. 31. 31. 31. 31.
 31. 29. 30. 29. 29. 28. 29. 29. 27. 31. 31. 30.]

The weekly averages are as follows:
 Week 1 : 30.714285714285715 
 Week 2 : 30.714285714285715 
 Week 3 : 30.571428571428573 
 Week 4 : 28.857142857142858
